# Generated by Django 6.0.5 on 2026-05-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agendamentos', '0002_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='nome_completo',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='endereco',
        ),
        migrations.AddField(
            model_name='perfil',
            name='cep',
            field=models.CharField(default='', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='cidade',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='estado',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='numero',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='rua',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
